- hosts: localhost

  tasks:
  - name: get variables
    include_vars: variables.yaml

  - name: "login-roks : Login to IBM Cloud"
    shell: |
      ibmcloud login --apikey "{{ ibmcloud_apikey }}" -q --no-region
    register: login_result
    retries: 10
    delay: 30
    until: login_result.rc == 0

  - name: "login-roks : Set the target cluster"
    shell: |
      ibmcloud oc cluster config -c {{ cluster_name }} --admin
    register: config_result
    retries: 10
    delay: 30
    until: config_result.rc == 0

  - name: "Lookup MAS superuser credentials"
    kubernetes.core.k8s_info:
      api_version: v1
      kind: Secret
      name: "{{ mas_instance_id }}-credentials-superuser"
      namespace: "{{mas_namespace}}"
    register: superuser_credentials
  
  - name: "Show the username/password"
    set_fact:
      superuser_username: "{{ superuser_credentials.resources[0].data.username | b64decode }}"
      superuser_password: "{{ superuser_credentials.resources[0].data.password | b64decode }}"
  
  - name: Lookup Route for admin
    kubernetes.core.k8s_info:
      api_version: route.openshift.io/v1
      kind: Route
      name: "{{ mas_instance_id}}-admin"
      namespace: "{{ mas_namespace }}"
    register: admin_route

  - name: "Lookup cluster subdomain"
    kubernetes.core.k8s_info:
      api_version: config.openshift.io/v1
      kind: Ingress
      name: cluster
    register: cluster_subdomain

  - debug:
      msg:
        - "Maximo Application is Ready, use the superuser credentials to authenticate"
        - "Admin Dashboard ... https://{{ admin_route.resources[0].spec.host }}/"
        - "Username .......... {{ superuser_username }}"
        - "Password .......... {{ superuser_password }}"
        - "Subdomain ......... {{ cluster_subdomain.resources[0].spec.domain }}"
  
